#!/bin/bash

options=(
	style=round     # round or square
	active_color=0xff38bdf8         # 0xffc4b5fd             # 0xffe1e3e4
	inactive_color=0xffbfdbfe               # 0xff494d64
    background_color=0xffc4b5fd          # Sets the background fill color for all windows
    width=7.0 
    hidpi=on                               # If set to on, the border will be drawn with retina resolution.
    # blacklist=<application_list>
    whitelist=inactive
)

borders "${options[@]}"