#!/bin/bash

options=(
	style=round                     # round or square
	active_color=0xff38bdf8         # 0xffc4b5fd 
	inactive_color=0xffbfdbfe       # 0xff494d64
    background_color=0xffc4b5fd     # Sets the background fill color for all windows
    width=6.0 
    hidpi=on                        # If set to on, the border will be drawn with retina resolution.
)

borders "${options[@]}"